FROM node:alpine AS base
# FROM node:10.24.0-alpine3.10 AS base

# > different docker CLI prep commands to preload various images
# docker pull node:alpine
# docker pull alpine:3.12.4
# docker pull node:10.24.0-alpine3.10
# docker pull node:15.11.0-alpine3.13

FROM base AS build
WORKDIR /app
COPY package*.json ./
RUN yarn install
COPY . .

ONBUILD RUN yarn build

EXPOSE 3000
CMD ["yarn", "start"]